// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjpMiJbV5nTTVaQcFTH-70metGeWfh73I',
    appId: '1:819027696392:web:fd33e51d13b6bf4ffaaabd',
    messagingSenderId: '819027696392',
    projectId: 'mabar-slurd',
    authDomain: 'mabar-slurd.firebaseapp.com',
    storageBucket: 'mabar-slurd.firebasestorage.app',
    measurementId: 'G-M4WKK2XSCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKesGeInT4Nkd1O_TGraDdotMq7mPVX5A',
    appId: '1:819027696392:android:ea7d0cb436571d9dfaaabd',
    messagingSenderId: '819027696392',
    projectId: 'mabar-slurd',
    storageBucket: 'mabar-slurd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdyONuDsdxg78FUZRC5Lo2_gTrm-rJtT8',
    appId: '1:819027696392:ios:4fe369c73cf4933dfaaabd',
    messagingSenderId: '819027696392',
    projectId: 'mabar-slurd',
    storageBucket: 'mabar-slurd.firebasestorage.app',
    iosBundleId: 'com.example.mabarSlurd',
  );
}
